name: Test if shit breaks

on:
  push:
    branches:
      - remove-tracking

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_deploy_linux:
    name: Linux builds go brrrrrr
    runs-on: ubuntu-latest
    timeout-minutes: 80

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install project dependencies
        run: pnpm install

      - name: Apply the Patch
        run: git apply < adsbegone-gdlauncher-carbon.patch

      - name: Generate Prisma Code and RSPC Bindings
        run: pnpm codegen

      - name: Build Application for Linux
        run: pnpm build:linux-x64