name: Build and Deploy GDLauncher

on: push
env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_deploy_linux:
    name: Build and Deploy (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install project dependencies
        run: pnpm install

      - name: Apply the Patch
        run: git apply < adsbegone-gdlauncher-carbon.patch

      - name: Setup Environment Variables
        run: echo "USER_AGENT_PREFIX = \"\"\nMS_AUTH_CLIENT_ID = \"\"\nMETA_BASE_URL = \"\"\nBASE_API = \"\"\nRUNTIME_PATH = \"\"" > .env

      - name: Generate Prisma Code and RSPC Bindings
        run: pnpm codegen

      - name: Build Application for Linux
        run: pnpm build:linux-x64

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: gdlauncher-linux-x64
          path: dist/linux-unpacked/

  build_and_deploy_macos:
    name: Build and Deploy (macOS)
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install project dependencies
        run: pnpm install

      - name: Apply the Patch
        run: git apply < adsbegone-gdlauncher-carbon.patch

      - name: Setup Environment Variables
        run: echo "USER_AGENT_PREFIX = \"\"\nMS_AUTH_CLIENT_ID = \"\"\nMETA_BASE_URL = \"\"\nBASE_API = \"\"\nRUNTIME_PATH = \"\"" > .env

      - name: Generate Prisma Code and RSPC Bindings
        run: pnpm codegen

      - name: Build Application for macOS
        run: pnpm build:mac-x64

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: gdlauncher-macos-x64
          path: dist/mac/

  build_and_deploy_windows:
    name: Build and Deploy (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install project dependencies
        run: pnpm install

      - name: Apply the Patch
        run: git apply < adsbegone-gdlauncher-carbon.patch

      - name: Setup Environment Variables
        run: echo "USER_AGENT_PREFIX = \"\"\nMS_AUTH_CLIENT_ID = \"\"\nMETA_BASE_URL = \"\"\nBASE_API = \"\"\nRUNTIME_PATH = \"\"" > .env

      - name: Generate Prisma Code and RSPC Bindings
        run: pnpm codegen

      - name: Build Application for Windows
        run: pnpm build:win-x64

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: gdlauncher-win-x64
          path: dist/win-unpacked/
